artsy/renovate-config

- package.json
Currently renovate only includes version to version diff links. This'll add an extra note that includes a link of all the changes. 
I found documentation on the feature [here](https://renovatebot.com/docs/configuration-options/#prbodynotes) and I found the variables I could access from [here](https://github.com/renovatebot/renovate/blob/608d8c5be081cd8f001f64c632aca87db0ceedb0/lib/config/templates/default/pr-body.hbs).
> [FEATURE config] Add a PR note with a link to the full change set

- .circleci/config.yml
I was looking at a workflow and noticed there wasn't a line connecting tests to deploy. 
That meant that the deployment could happen without the tests passing, which was _not_ intentional.
Fixed now!
> Ensure deploy ci step relies on tests completing

- renovate.json
_config:base_ adds some restrictions on how many concurrent PRs can be open. This removes those so it can open as many PRs as it needs. This applies only to this repository's configuration, not to other projects.
> [PATCH config] remove limits on PRs

- package.json
Adds a new artsy config that can be used to enable updating node. For now it just targets docker images for hokusai projects.
> Enable updating node versions inside of docker files

- package.json
@rarkins [made an update](https://github.com/renovatebot/renovate/commit/772bc176037e377369e94018f7d44eb19393736f) that changed `repositoryUrl` to `sourceUrl`. This PR should fix our PR show-more links. 
By the way @rarkins, this might be a good thing to actually put in the main PR template. Here's an example of it in use: https://github.com/artsy/positron/pull/1810
> Fix the full list changes link

- package.json
Volt uses the [`nonOfficeHours`](https://github.com/artsy/volt/blob/9ea77bf8d1f91c54232281b8428ef9543781b4e8/renovate.json#L4) preset for scheduling and it's in UTC, which might compete with real people, given a Volt build tends to take some time.
[Timezone][1] is used for setting schedules, and the [default][2] is the timezone of the machine that renovate is running on. It's probably better to have a consistent timezone across organization and each app can override it locally if needed.
This sets the default to the timezone of Artsy HQ.
[1]: https://renovatebot.com/docs/configuration-options/#timezone
[2]: https://renovatebot.com/docs/faq/#control-renovates-schedule
> Set default timezone to EST for consistent use of schedules

- .circleci/config.yml
This adds a step to the CI build that runs [auto pr-check](https://intuit.github.io/auto-release/pages/auto-pr-check.html). It'll give us early warning of any issues with auto-check as well as generally just making sure the labels are set correctly on this repo.
> Add auto-release PR check

- .circleci/config.yml
The PR check should only really ever be used on branches that aren't master. Otherwise it's just a waste of time and CI resources.
> Don't run pr-check on master

- package.json
This adds a new package rule to (hopefully) mark all `devDependency` updates as `Version: Trivial`. This is to preserve my sanity, ha.
> Make all devDependency updates marked as trivial

- package.json
This is intended to be merged in conjunction with https://github.com/artsy/orbs/pull/17. It'll remove the updating of `auto-release-cli` by renovate. Post this PR I'll remove `auto-release-cli` as a direct dependency from each of our projects.
> Remove automatic updating of auto-release-cli

- package.json
Fixes #152
When I enabled circleci updates so that our orbs would get bumped it also started bumping docker images in the circleci config. I could explicitly ignore them all, but `artsy/hokusai` is the one that's cropped up a few times. This'll just make sure we ignore it going forward. We can always remove this property if it's needed later.
> Explicitly ignore artsy/hokusai in circleci config

- package.json
When an update happens to our configs, we should auto update. This will _only_ apply to minor or patch updates. Major updates will still need to be manually merged (because it might be a breaking change for the project).
> Automerge auto config and yarn orb

- package.json
This runs [yarn-deduplicate](https://github.com/atlassian/yarn-deduplicate) (with the `highest` option) when updating dependencies w/ renovate. 
See the docs [here](https://renovatebot.com/docs/configuration-options/#postupdateoptions).
> Run yarn dedupe on dependency updates

- package.json
The dedupe process is _potentially_ causing issues, specifically in positron. I'm disabling it to see if it has any effect.
> Remove dedupe process from renovate

- package.json
Enables the [master issue approval](https://renovatebot.com/blog/master-issue) workflow so we have more granular control over non-artsy dependencies.
> Adds new approval workflow

- package.json
For whatever reason the approval workflow wasn't doing what I expected. My hunch is that even though I was extending the default workflow, the rule in approval _wasn't_ overriding the rule in default. 
For now I've just copied the whole thing. Hopefully this'll correctly enable the approval workflow.
> Make approval workflow duplicate of default

- lib/config-builder.js
- package.json
@rarkins [fixed the issue](https://github.com/renovatebot/renovate/commit/1dfcc4ef3d043ef1dc96c64eab512c597d7664f9) that required the `masterIssue` flag on the top level config to get the `masterIssueApproval` workflow to work.
> Remove global master issue flag as it's no longer needed

- lib/config-builder.js
- package.json
Just upgraded metaphysics to use the `@artsy:app` preset and it added a trivial label to one of the PRs. 
I removed it from the shared preset so it's not applied to apps.
> Don't use version label on apps

- lib/config-builder.js
- package.json
This makes auto-merging non-major changes automatic across the board. Also it moves the `See full changes...` PR comment that's specific to our dependencies to an artsy only package rule.
> auto merge minors by default, make artsy specific pr comments

- lib/config-builder.js
- package.json
This'll group all the dependencies we check in the master approval list into a single PR.
> Create a group for non-artsy dependencies

- lib/config-builder.js
- package.json
There's not any way to smartly determine if a dependency update constitutes a breaking change and we generally don't want to release when there's a dependency update so always just set it to trivial.
> Always default to trivial on dep updates

- lib/config-builder.js
- package.json
- tests/validate-config.test.js
The `lib` config was absolutely borked. I messed up some object merging in the generation and `lib` stopped extending from `shared` which is where all the rules live. It basically turned it into a raw instance of renovate. 
I've got a test in place now to ensure that doesn't happen again.
> Fix malformed @artsy:lib config

- lib/config-builder.js
- package.json
cc @damassi, @alloy, @ds300 
I updated packages in the `@omakase` scope to be treated exactly like `@artsy`. That means when there's an update for them we'll get a PR automatically, and if it's a minor/patch it'll be automerged.
> Create dep PRs for any omkase packages

- lib/config-builder.js
- package.json
As per [this slack thread](https://artsy.slack.com/archives/CA8SANW3W/p1559161959176500) I've disabled security updates for renovate. 
We're just going to use GitHub's built-in functionality instead. 
cc @dleve123
> Don't do security PRs w/ renovate

- lib/config.js
- lib/generate-config.js
- package.json
- tests/validate-config.test.js
Renovate has a notion of pinning dependencies. It does this to provide more transparency/consistency around the current version. This puts the versions in the `package.json` in line with the versions of the lock file. 
These changes are non-breaking and it always keeps the same version that's configured in the lock file. Give that, we should just auto merge these PRs.
> Rename config, automatically merge pins

- lib/config.js
- package.json
I noticed that some of our orb updates weren't getting PRs. After discussing with @rarkins in https://github.com/renovatebot/config-help/issues/300 it seems it might've been inheriting a docker setting that disabled it for major releases. 
I've manually overridden that here.
> Fix an issue w/ orbs not getting PRs on major updates

- .circleci/config.yml
- lib/config.js
- package.json
- tests/validate-config.test.js
- yarn.lock
This groups all the packages from react's official repo into a single dependency update. Useful if we ever want to use renovate to update react.
> Group react dependencies together

- lib/config.js
- package.json
In the long run, this would be part of the `@omakase/dev` meta-package, but we’re not even using that yet in Emission.
---
This repository uses [auto](https://github.com/intuit/auto) to generate releases. In order to do that, 
it needs an appropriate label assigned to each PR. Choose a label below that you feel best suites your changes.
##
<sub>**Semver Labels** _(choose at most one)_</sub>
##
<sub>**Skip Release Labels** _(chose at most one)_</sub>
<sub>_Generated by [auto-it](https://github.com/apps/auto-it)_</sub>
> [config] Create PRs for vscode-apollo-relay

- lib/config.js
- package.json
After opening https://github.com/artsy/kaws/pull/160 I noticed that renovate was trying to automerge it. Generally, I think it's best practice that we _never_ automerge a non-artsy dependency unless we're doing it through merge on green. 
---
This repository uses [auto](https://github.com/intuit/auto) to generate releases. In order to do that, 
it needs an appropriate label assigned to each PR. Choose a label below that you feel best suites your changes.
##
<sub>**Semver Labels** _(choose at most one)_</sub>
##
<sub>**Skip Release Labels** _(chose at most one)_</sub>
<sub>_Generated by [auto-it](https://github.com/apps/auto-it)_</sub>
> Ensure non-artsy dependencies aren't automerged

- lib/config.js
- package.json
Some extra context here: https://artsy.slack.com/archives/CP9P4KR35/p1587502585324600
There were some resolutions added to radiation that automatically got renovate PRs opened for them. This was unexpected. It seems like `resolutions` was added as a new depTypeList in https://github.com/renovatebot/renovate/pull/5689.
We added it to our generate master issue approval flow so updates to this will get triggered in the issue update but won't spawn a new PR.
> Add resolutions to the master issue approval flow

- lib/config.js
- package.json
Typescript does not follow semantic versioning, so minor upgrades have been auto-merged and disrupted our release pipelines on [multiple](https://github.com/artsy/force/pull/12111) [occasions](https://github.com/artsy/force/pull/10850) and [across](https://github.com/artsy/prediction/pull/1225) different projects.
I _think_ this will continue to allow renovate to make upgrade PRs, but they won't be auto-merged. Not sure how to test it though.
> fix: avoid auto-merging breaking typescript upgrades
