- package.json
Noticed an issue where the URLs were slightly off (missing the `v`s). This should fix it.
> Fixes issue where comparison link was broken

- .autorc
- package.json
- yarn.lock
Moves from semantic release to auto release.
> Switch to auto-release

- .circleci/config.yml
- package.json
I forgot to update circle's config when setting up auto-release...
> Correct ci to use auto-release

- package.json
I really don't want to keep having to make PRs all over the place for `auto-release-cli`. Gonna automate it... hopefully.
> Allow the auto-updating of auto-release-cli

- package.json
> Fix auto-release-cli not updating

- .autorc
Fixes a config incompatibility
> Updates autorc to support v2

- package.json
> Include peerDependencies in node package updates

- package.json
> Ensure Orb updates are treated as trivial

- .circleci/config.yml
- package.json
This should _hopefully_ only ignore the engines fields.
> Ignore engine updates

- .circleci/config.yml
Bumps the orbs so CI works again
> Bump yarn orb

- .circleci/config.yml
There was another issue w/ the auto-release command. This hopefully bump hopefully resolves that.
> Bump yarn orb again

- .circleci/config.yml
The last of the mulligans... I HOPE.
> Bump yarn orb version

- .autorc
- package.json
- yarn.lock
Use's artsy's [shared auto config](https://github.com/artsy/auto-config).
> Use artsy shared auto config

- .circleci/config.yml
Updates the yarn orb to make it easier to debug auto
> Update yarn orb

- package.json
Working through suggestions in https://github.com/renovatebot/config-help/issues/224 to try to fix the master issue approval workflow.
> Add masterIssue to attempt to force masterIssueApproval

- lib/config-builder.js
- lib/generate-config.js
- package.json
- tests/validate-config.test.js
- yarn.lock
Adds two new configs: app & lib. 
They should be used like
```json
{
"extends": ["@artsy:app"]
}
```
They have different version pinning strategies to match proper app dev
> Add app & lib presets

- lib/config-builder.js
- package.json
After we select an update from the master issue it should auto merge if it's a patch or minor.
> Automerge minors on issue approvals

- lib/config-builder.js
- package.json
Ensure masterApproval updates are automerged
> Ensure minor dep updates are automerged

- renovate.json
> Use renovate lib workflow

- lib/config-builder.js
- package.json
I noticed orbs PRs weren't being trigged so I'm explicitly setting the orb flag to be enabled. 
Hopefully this fixes it. 🤞
> Explicitly ensure orb updates are enabled

- lib/config.js
- package.json
Fixes [PLATFORM-1723](https://artsyproduct.atlassian.net/browse/PLATFORM-1723).
---
This repository uses [auto](https://github.com/intuit/auto) to generate releases. In order to do that, 
it needs an appropriate label assigned to each PR. Choose a label below that you feel best suites your changes.
##
<sub>**Semver Labels** _(choose at most one)_</sub>
##
<sub>**Skip Release Labels** _(chose at most one)_</sub>
<sub>_Generated by [auto-it](https://github.com/apps/auto-it)_</sub>
> Group babel dependencies together into a single update

- lib/config.js
- package.json
This _should_ automatically update (and merge if green) typescript
> Automatically update typescript

- lib/config.js
- package.json
Related conversation: https://artsy.slack.com/archives/C02BC3HEJ/p1594825173491100
> Add optionalDependencies to depTypeList

- .circleci/config.yml
- CHANGELOG.md
Favor inclusive language in the codebase per this [RFC][].
[RFC]: artsy/README#427
> feat: adopt inclusive language - main default branch

- README.md
Expand the README to also include steps on how to update renovate global configuration to add an integration to the project.
> docs: steps for how to integrate renovate into a project
